name: sync
description: A library for managing asynchronous processes inspired by the Go sync package.
version: 0.3.0
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-sync

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ">=1.16.2 <2.0.0"
